home/urls.py
from django.conf.urls import url
from django.conf.urls.i18n import i18n_patterns

from .views import *


urlpatterns = [

	url(r'^log-out/$', log_out, name='log-out'),
	url(r'^sign-in/$', sign_in, name='sign_in'),
	# url(r'^d/change-password/$', change_password, name='change-password'),
	url(r'^$', dashboard, name='dashboard'),
	url(r'^work-page-search/a/$', work_page_search, name='work-page-search'),
	url(r'^employee-search-works/a/$', employee_search, name='employee-search-works'),
	url(r'^general-all-user/(?P<u_slug>[\w-]+)/$', general_all_user, name='general-all-user'),
	# url(r'^general-all-user/(?P<pk>[\w-]+)/remove/$', general_all_user_remove, name='general-all-user-remove'),
	url(r'^employee-page/(?P<e_id>[\w-]+)/places/$', employee_page_places, name='employee-page-places'),
	url(r'^employee-page/(?P<e_id>[\w-]+)/$', employee_page, name='employee_page'),
	url(r'^customer-page/(?P<c_id>[\w-]+)/$', customer_page, name='customer-page'),
	url(r'^employee-page-search/(?P<e_id>[\w-]+)/$', employee_page_search, name='employee-page-search'),
	url(r'^employee-location/(?P<e_id>[\w-]+)/(?P<day>[0-9]{2})-(?P<month>[0-9]{2})-(?P<year>[0-9]{4})/$', employee_day_checks, name='employee-day-checks'),
	url(r'^employee-add-to-customer/$', employee_add_to_customer, name='employee-add-to-customer'),
	url(r'^my-works-list/c/$', customer_works_list, name='customer-works-list'),
	url(r'^add-user/$', sign_up, name='sign-up'),
	url(r'^edit-user/(?P<user_type>[\w-]+)/(?P<user_id>[\w-]+)/$', edit_user, name='edit-user'),
	url(r'^remove-user/(?P<user_type>[\w-]+)/(?P<pk>[\w-]+)/$', general_all_user_remove, name='remove-user'),
	url(r'^customer/place/list/$', company_list, name='company-list'),
	url(r'^customer/place/create/$', company_create, name='company-create'),
	url(r'^customer/place/edit/(?P<p_id>[\w-]+)/$', company_edit, name='company-edit'),
	url(r'^customer/place/remove/(?P<p_id>[\w-]+)/$', company_remove, name='company-remove'),

]

workchecker/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.contrib.auth.decorators import login_required
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.utils import translation
from django.views import generic
from django.views.static import serve
from home.views import *
from django.views import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^administration/', admin.site.urls,name="admin"),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
        url(r'^media/(?P<path>.*)$', static.serve, {'document_root': settings.MEDIA_ROOT }, name='media')
]

urlpatterns += [
    url(r'^', include("home.urls", namespace="home")),
]

urlpatterns += staticfiles_urlpatterns()




@login_required
def protected_serve(request, path, document_root=None, show_indexes=False):
    return serve(request, path, document_root, show_indexes)


if settings.DEBUG is False:   #if DEBUG is True it will be served automatically
    urlpatterns += [
        url(r'^static/(?P<path>.*)$', static.serve, {'document_root': settings.STATIC_ROOT }, name='static'),
        url(r'^media/(?P<path>.*)$', static.serve, {'document_root': settings.MEDIA_ROOT }, name='media')
    ]
urlpatterns += staticfiles_urlpatterns()

home/views.py
import copy
import json
import uuid
from datetime import timedelta
import firebase_admin
from django.conf import settings
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, Http404, HttpResponse, JsonResponse
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import authenticate

from django.contrib.auth.views import logout
# Create your views here.
from django.template.loader import render_to_string
from django.urls import reverse
from django.utils import timezone
from django.utils.datetime_safe import datetime, date
import datetime as pyt_datetime
import pyrebase
from geoposition import Geoposition

from home.forms import *
import uuid

from django.utils.translation import ugettext as _
# Create your views here.
from home.functions import check_dict_key, split_text
from home.tasks import remove_place_task, remove_user

firebase = pyrebase.initialize_app(settings.FB_CONFIG)
auth_fb = firebase.auth()
database_fb = firebase.database()
storage_fb = firebase.storage()

from firebase_admin import credentials, firestore, auth as fs_auth

from workchecker.settings import BASE_DIR

cred = credentials.Certificate(os.path.join(BASE_DIR, 'static/system/workertracker-ed2f5-firebase-adminsdk-6fw4q-1dbf39de56.json'))
app = firebase_admin.initialize_app(cred)

store = firestore.client()




def base(req=None):
    data = {
        'now':datetime.now(),
        'base_site_name' : settings.SITE_NAME,
    }
    return data

def check_user(req=None):
    return_val = [0,None,None,None]
    session_expiry_date = req.session.get_expiry_date()
    # # print("---------  session_expiry_date = {}".format(session_expiry_date))
    # if not check_valid_session(req):
    #     auth.logout(req)
    try:
        idtoken = req.session['token']
        uid = req.session['uid']
        profile_val = req.session['user_profile']
        user_type = req.session['user_type']
        email = req.session['email']
        if idtoken and uid and profile_val and email:
            profile_val['id'] = uid
            profile_val['email'] = email
            profile_val['user_type'] = user_type
            return_val = [1,idtoken,uid,profile_val]
    except:
        pass
    return return_val

def check_valid_session(request):
    return_val = True
    session_expiry_date = request.session.get_expiry_date()
    now = pyt_datetime.datetime.now()
    # # print("----------------------------------")
    # # print(type(session_expiry_date))
    # # print(type(now))
    # seconds_left = (session_expiry_date - now)
    # # # print("seconds_left == {}".format(seconds_left))
    if session_expiry_date.date() <= now.date():
        return_val = False
    return return_val

def base_auth(req=None):
    #
    # try:
    #     req.session['uid']
    # except:
    #     return HttpResponseRedirect(reverse('home:sign_in'))
    data = {
        'now':datetime.now(),
        'base_site_name' : settings.SITE_NAME,
    }
    user = check_user(req=req)
    # # # print("-----------------------------------------------------------")
    # # # print(user)
    # # # print(user[3])
    # # # print("____________________________________________________________")
    if user[0] == 1:
        # user_profile_val = user[3]
        user_profile = user[3]
        data.update({'base_user_profile':user_profile})
    else:
        data.update({'base_user_profile':None})
        # # # print("data['base_user_profile']  = {}".format(data['base_user_profile']))
    return data



# auth.

def sign_in(request):
    login_form = LoginForm(request.POST or None)

    auth.logout(request)
    next_url = request.GET.get('next_url')
    context = base(req=request)
    context['login_form'] = login_form
    context['next_url'] = next_url
    # return HttpResponse(next_url)
    if request.method == 'POST':
        if login_form.is_valid():
            clean_data = login_form.cleaned_data
            email = clean_data.get('username_or_email')
            password = clean_data.get('password')

            # if remember_me:
            #     remember_me = True
            # else:
            #     remember_me = False
            #     remember_me = False
            try:
                user = auth_fb.sign_in_with_email_and_password(email=email,password=password)
                # return HttpResponse(next_url)
                if next_url == 'None' or not next_url:
                    next_url = reverse('home:dashboard')
                else:
                    pass
                # # print('next_url={}')
                # return HttpResponse(next_url)
                # print("user={}".format(user))
                session_id = user['idToken']
                ui_id = user['localId']
                request.session['uid'] = str(ui_id)
                request.session['token'] = str(session_id)
                log_out_bool = False
                user_profile = None
                user_type = 0
                user_query = store.document('users/{}'.format(ui_id)).get().to_dict()
                # print(user_query)
                if user_query and user_query['type'] and (user_query['type'] == 1 or user_query['type'] == 2):
                    user_type = user_query['type']

                    if user_type == 1:
                        user_profile = store.document('admins/{}'.format(ui_id)).get().to_dict()
                    elif user_type == 2:
                        user_profile = store.document('customers/{}'.format(ui_id)).get().to_dict()

                request.session['user_profile'] = user_profile
                request.session['user_type'] = user_type


                request.session.set_expiry(204800)
                # # print("^^^---^^^ user_profile = {}".format(user_profile))
                if user_profile:
                    request.session['email'] = email
                else:
                    auth.logout(request)
                    return render(request, 'home/general/sign-in.html', context=context)
                return HttpResponseRedirect(next_url)
            except:
                message_login = _("Email or Password is incorrect")
            context['message_login'] = message_login

            # else:

    return render(request, 'home/general/sign-in.html', context=context)




def log_out(request):
    if check_user(req=request)[0]:
        auth.logout(request)
    else:
        auth.logout(request)
    return HttpResponseRedirect(reverse('home:sign_in'))



def dashboard(request):
    now = timezone.now()
    context = base_auth(req=request)
    user_profile = context['base_user_profile']

    # all_employees = store.collection(u'employees').get()
    # i_c = 0
    # for all_employees_item in all_employees:
    #     i_c += 1
    #     # if i_c >2:
    #     #     break
    #     try:
    #         all_employees_item_uid = all_employees_item.id
    #         user = fs_auth.get_user(all_employees_item_uid)
    #         user_ref = store.collection('employees').document("{}".format(all_employees_item_uid)).set({'email':user.email}, merge=True)
    #         # print("user = {}".format(user.email))
    #     except:
    #         pass
    if context['base_user_profile'] is None:
        return HttpResponseRedirect(reverse('home:sign_in')+"?next_url="+reverse('home:dashboard'))

    context['work_search_form'] = WorkSearchForm(request.POST or None, )

    # # print("context['base_user_profile']['user_type'] = {}".format(user_profile))

    if user_profile['user_type']:
        work_search_form = WorkSearchForm(request.POST or None,initial={'date':'{}'.format(now.strftime('%d-%m-%Y'))})
        context['work_search_form'] = work_search_form
    else:
        raise Http404
    return render(request, 'home/general/dashboard.html', context=context)



def general_all_user(request,u_slug):
    context = base_auth(req=request)
    if context['base_user_profile'] is None:
        return HttpResponseRedirect(reverse('home:sign_in')+"?next_url="+reverse('home:general-all-user', kwargs={'u_slug':u_slug}))

    if context['base_user_profile']['user_type'] == '1' or context['base_user_profile']['user_type'] == 1:
        pass
    else:
        raise Http404
    # # print("--------------------------------------------")
    if u_slug == 'customers':
        page_title = _('Customers')
    elif u_slug == 'employees':
        page_title = _('Employees')
    else:
        raise Http404
    if request.method == 'POST' and request.is_ajax():
        if u_slug == 'customers':
            all_users = store.collection(u'customers').get()
        else:
            all_users = store.collection(u'employees').get()
        _html = ''
        _result_html = ''
        all_users_item_i = 0
        for all_users_item in all_users:
            all_users_item_val = all_users_item.to_dict()
            if check_dict_key(all_users_item_val, 'deleted'):
                continue
            all_users_item_i += 1
            if u_slug == 'customers':
                _html = "{}{}".format(_html,
                                      render_to_string(
                                          'home/include/user-list/customer-row-item.html',
                                          {
                                              'index':all_users_item_i,
                                              'list_item_id':all_users_item.id,
                                              'list_item':all_users_item_val,
                                          })
                                      )
            elif u_slug == 'employees':
                _html = "{}{}".format(_html,
                                      render_to_string(
                                          'home/include/user-list/employee-row-item.html',
                                          {
                                              'index':all_users_item_i,

templates/home/general/employee-list.html
{% extends 'main_base.html' %}
{% load static %}
{% load i18n %}
{% block title_container %}
    {% trans 'Employees' %}
{% endblock %}


{% block head_container %}
{% endblock %}
{% block head_under_container %}

        <!-- BEGIN PAGE LEVEL PLUGINS -->
        <link href="{% static 'main/assets/global/plugins/datatables/datatables.min.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'main/assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css' %}" rel="stylesheet" type="text/css" />
        <!-- END PAGE LEVEL PLUGINS -->

{% endblock %}


{% block content_container %}

            <!-- BEGIN CONTENT -->
            <div class="page-content-wrapper">
                <!-- BEGIN CONTENT BODY -->
                <div class="page-content">
                    <!-- BEGIN PAGE HEAD-->
                    <div class="page-head">
                        <!-- BEGIN PAGE TITLE -->
                        <div class="page-title">
                            <h1>Employees
{#                                <small>responsive extension demos</small>#}
                            </h1>
                        </div>
                        <!-- END PAGE TITLE -->
                    </div>
                    <!-- END PAGE HEAD-->
                    <!-- BEGIN PAGE BREADCRUMB -->
                    <ul class="page-breadcrumb breadcrumb">
                        <li>
                            <a href="{% url 'home:dashboard' %}">Dashboard</a>
                            <i class="fa fa-circle"></i>
                        </li>
                        <li>
                            <span class="active">Employees</span>
                        </li>
                    </ul>
                    <!-- END PAGE BREADCRUMB -->

                    <div class="row">
                        <div class="col-md-12">
                            <!-- BEGIN EXAMPLE TABLE PORTLET-->
                            <div class="portlet box red">
                                <div class="portlet-title">
                                    <div class="caption">
                                        <i class="fa fa-globe"></i>Employees List</div>
                                    <div class="tools"> </div>
                                </div>
                                <div class="portlet-body">
                                    <table class="table table-striped table-bordered table-hover dt-responsive" width="100%" id="sample_4">
                                        <thead>
                                            <tr>
                                                <th class="all">Photo</th>
                                                <th class="all">Full name</th>
                                                <th class="min-tablet">Status</th>
                                                <th class="min-tablet">Phone</th>
                                                <th class="min-tablet">Actions</th>
{#                                                <th class="none">Id</th>#}
{#                                                <th class="none">User Type</th>#}
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for all_data_list_item in all_data_list %}
                                                <tr>
                                                    <td>
                                                        <a href="{% if all_data_list_item.image %}{{ all_data_list_item.image }}{% else %}{% static 'main/assets/pages/media/users/icon-user.png' %}{% endif %}" class="example-image-link" data-lightbox="example-1"><img class="example-image"  style="height:50px;" src="{% if all_data_list_item.image %}{{ all_data_list_item.image }}{% else %}{% static 'main/assets/pages/media/users/icon-user.png' %}{% endif %}"></a>
                                                    </td>
                                                    <td>{{ all_data_list_item.name }}</td>
                                                    <td>{% if all_data_list_item.status %}
                                                            <span class="badge badge-success"> ✓ </span>
                                                        {% else %}
                                                            <span class="badge badge-danger"> x </span>
                                                        {% endif %}
                                                    </td>
                                                    <td>{{ all_data_list_item.phone }}</td>
                                                    <td>
                                                        <a href="{% url 'home:employee_page' all_data_list_item.id %}" class="btn dark btn-sm btn-outline sbold uppercase">
                                                            <i class="fa fa-eye"></i> View </a> |
                                                        <a href="{% url 'home:edit-user' 'employee' all_data_list_item.id %}" class="btn btn-outline btn-circle btn-sm purple">
                                                            <i class="fa fa-edit"></i> Edit </a>
                                                    </td>
{#                                                    <td>{{ all_data_list_item.id }}</td>#}
{#                                                    <td>{{ all_data_list_item.user_type }}</td>#}
                                                </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <!-- END EXAMPLE TABLE PORTLET-->
                        </div>
                    </div>
                    <!-- END PAGE BASE CONTENT -->
                </div>
                <!-- END CONTENT BODY -->
            </div>
            <!-- END CONTENT -->

{% endblock %}


{% block js_block %}


        <!-- BEGIN PAGE LEVEL PLUGINS -->
        <script src="{% static 'main/assets/global/scripts/datatable.js' %}" type="text/javascript"></script>
        <script src="{% static 'main/assets/global/plugins/datatables/datatables.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'main/assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js' %}" type="text/javascript"></script>
        <!-- END PAGE LEVEL PLUGINS -->
        <!-- BEGIN THEME GLOBAL SCRIPTS -->
        <script src="{% static 'main/assets/global/scripts/app.min.js' %}" type="text/javascript"></script>
        <!-- END THEME GLOBAL SCRIPTS -->
        <!-- BEGIN PAGE LEVEL SCRIPTS -->
        <script src="{% static 'main/assets/pages/scripts/table-datatables-responsive.min.js' %}" type="text/javascript"></script>
        <!-- END PAGE LEVEL SCRIPTS -->

{% endblock %}

templates/home/general/sign-in.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>

<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
    <!--<![endif]-->
    <!-- BEGIN HEAD -->

    <head>
        <meta charset="utf-8" />
        <title>{% trans 'Sign in' %} | </title>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta content="Preview page of Metronic Admin Theme #4 for " name="description" />
        <meta content="" name="author" />
        <!-- BEGIN GLOBAL MANDATORY STYLES -->
        <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css" />
        <link href="{% static 'main/assets/global/plugins/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'main/assets/global/plugins/simple-line-icons/simple-line-icons.min.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'main/assets/global/plugins/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'main/assets/global/plugins/bootstrap-switch/css/bootstrap-switch.min.css' %}" rel="stylesheet" type="text/css" />
        <!-- END GLOBAL MANDATORY STYLES -->
        <!-- BEGIN PAGE LEVEL PLUGINS -->
        <link href="{% static 'main/assets/global/plugins/select2/css/select2.min.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'main/assets/global/plugins/select2/css/select2-bootstrap.min.css' %}" rel="stylesheet" type="text/css" />
        <!-- END PAGE LEVEL PLUGINS -->
        <!-- BEGIN THEME GLOBAL STYLES -->
        <link href="{% static 'main/assets/global/css/components-md.min.css' %}" rel="stylesheet" id="style_components" type="text/css" />
        <link href="{% static 'main/assets/global/css/plugins-md.min.css' %}" rel="stylesheet" type="text/css" />
        <!-- END THEME GLOBAL STYLES -->
        <!-- BEGIN PAGE LEVEL STYLES -->
        <link href="{% static 'main/assets/pages/css/login.min.css' %}" rel="stylesheet" type="text/css" />
        <!-- END PAGE LEVEL STYLES -->
        <!-- BEGIN THEME LAYOUT STYLES -->
        <!-- END THEME LAYOUT STYLES -->
        <link rel="shortcut icon" href="favicon.ico" />
    </head>
    <!-- END HEAD -->

    <body class=" login">
        <!-- BEGIN LOGO -->
        <div class="logo">
            <a href="{% url 'home:dashboard' %}">
                <img src="{% static 'main/assets/pages/img/logo-big.png' %}" alt="" /> </a>
        </div>
        <!-- END LOGO -->
        <!-- BEGIN LOGIN -->
        <div class="content">
            <!-- BEGIN LOGIN FORM -->
            <form class="login-form" action="" method="post">
                {% csrf_token %}
                <h3 class="form-title font-green">{% trans 'Sign In' %}</h3>
                {% if message_login %}
                    <div class="alert alert-danger">
                        <button class="close" data-close="alert"></button>
                        <span> {{ message_login }} </span>
                    </div>
                {% endif %}
                <div class="form-group">
                    <!--ie8, ie9 does not support html5 placeholder, so we just show field title for that-->
                    <label class="control-label visible-ie8 visible-ie9">{% trans 'Username or Email' %}</label>
                    {{ login_form.username_or_email }}
                </div>
                <div class="form-group">
                    <label class="control-label visible-ie8 visible-ie9">{% trans 'Password' %}</label>
                    {{ login_form.password }}
                </div>
                <div class="form-actions">
                    <button type="submit" class="btn green uppercase">{% trans 'Login' %}</button>
                    <label class="rememberme check mt-checkbox mt-checkbox-outline text-right">
                    {{ login_form.remember_me }}{% trans 'Remember me' %}
                        <span></span>
                    </label>
                </div>
                <div class="create-account">
                    <p>
                        <a href="javascript:" id="forget-password" class="">{% trans 'Forgot Password?' %}</a>
                    </p>
                </div>
            </form>
            <!-- END LOGIN FORM -->
            <!-- BEGIN FORGOT PASSWORD FORM -->
            <form class="forget-form" action="" method="post">
                <h3 class="font-green">Forget Password ?</h3>
                <p> Enter your e-mail address below to reset your password. </p>
                <div class="form-group">
                    <input class="form-control placeholder-no-fix" type="text" autocomplete="off" placeholder="Email" name="email" /> </div>
                <div class="form-actions">
                    <button type="button" id="back-btn" class="btn green btn-outline">Back</button>
                    <button type="submit" class="btn btn-success uppercase pull-right">Submit</button>
                </div>
            </form>
            <!-- END FORGOT PASSWORD FORM -->
        </div>
        <div class="copyright"> {{ now.year }} © {% if base_company_information %} {{ base_company_information.company_name }} {% endif %}</div>
        <!--[if lt IE 9]>
<script src="{% static 'main/assets/global/plugins/respond.min.js' %}"></script>
<script src="{% static 'main/assets/global/plugins/excanvas.min.js' %}"></script> 
<script src="{% static 'main/assets/global/plugins/ie8.fix.min.js' %}"></script> 
<![endif]-->
        <!-- BEGIN CORE PLUGINS -->
        <script src="{% static 'main/assets/global/plugins/jquery.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'main/assets/global/plugins/bootstrap/js/bootstrap.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'main/assets/global/plugins/js.cookie.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'main/assets/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'main/assets/global/plugins/jquery.blockui.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'main/assets/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js' %}" type="text/javascript"></script>
        <!-- END CORE PLUGINS -->
        <!-- BEGIN PAGE LEVEL PLUGINS -->
        <script src="{% static 'main/assets/global/plugins/jquery-validation/js/jquery.validate.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'main/assets/global/plugins/jquery-validation/js/additional-methods.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'main/assets/global/plugins/select2/js/select2.full.min.js' %}" type="text/javascript"></script>
        <!-- END PAGE LEVEL PLUGINS -->
        <!-- BEGIN THEME GLOBAL SCRIPTS -->
        <script src="{% static 'main/assets/global/scripts/app.min.js' %}" type="text/javascript"></script>
        <!-- END THEME GLOBAL SCRIPTS -->
        <!-- BEGIN PAGE LEVEL SCRIPTS -->
        <script src="{% static 'main/assets/pages/scripts/login.min.js' %}" type="text/javascript"></script>
        <!-- END PAGE LEVEL SCRIPTS -->
        <!-- BEGIN THEME LAYOUT SCRIPTS -->
        <!-- END THEME LAYOUT SCRIPTS -->
        <script>
            $(document).ready(function()
            {
                $('#clickmewow').click(function()
                {
                    $('#radio1003').attr('checked', 'checked');
                });
            })
        </script>
    </body>

</html>