home/urls.py
from django.conf.urls import url
from django.conf.urls.i18n import i18n_patterns

from .views import *


urlpatterns = [

	url(r'^log-out/$', log_out, name='log-out'),
	url(r'^sign-in/$', sign_in, name='sign_in'),
	# url(r'^d/change-password/$', change_password, name='change-password'),
	url(r'^$', dashboard, name='dashboard'),
	url(r'^work-page-search/a/$', work_page_search, name='work-page-search'),
	url(r'^employee-search-works/a/$', employee_search, name='employee-search-works'),
	url(r'^general-all-user/(?P<u_slug>[\w-]+)/$', general_all_user, name='general-all-user'),
	# url(r'^general-all-user/(?P<pk>[\w-]+)/remove/$', general_all_user_remove, name='general-all-user-remove'),
	url(r'^employee-page/(?P<e_id>[\w-]+)/places/$', employee_page_places, name='employee-page-places'),
	url(r'^employee-page/(?P<e_id>[\w-]+)/$', employee_page, name='employee_page'),
	url(r'^customer-page/(?P<c_id>[\w-]+)/$', customer_page, name='customer-page'),
	url(r'^employee-page-search/(?P<e_id>[\w-]+)/$', employee_page_search, name='employee-page-search'),
	url(r'^employee-location/(?P<e_id>[\w-]+)/(?P<day>[0-9]{2})-(?P<month>[0-9]{2})-(?P<year>[0-9]{4})/$', employee_day_checks, name='employee-day-checks'),
	url(r'^employee-add-to-customer/$', employee_add_to_customer, name='employee-add-to-customer'),
	url(r'^my-works-list/c/$', customer_works_list, name='customer-works-list'),
	url(r'^add-user/$', sign_up, name='sign-up'),
	url(r'^edit-user/(?P<user_type>[\w-]+)/(?P<user_id>[\w-]+)/$', edit_user, name='edit-user'),
	url(r'^remove-user/(?P<user_type>[\w-]+)/(?P<pk>[\w-]+)/$', general_all_user_remove, name='remove-user'),
	url(r'^customer/place/list/$', company_list, name='company-list'),
	url(r'^customer/place/create/$', company_create, name='company-create'),
	url(r'^customer/place/edit/(?P<p_id>[\w-]+)/$', company_edit, name='company-edit'),
	url(r'^customer/place/remove/(?P<p_id>[\w-]+)/$', company_remove, name='company-remove'),

]

workchecker/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.contrib.auth.decorators import login_required
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.utils import translation
from django.views import generic
from django.views.static import serve
from home.views import *
from django.views import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^administration/', admin.site.urls,name="admin"),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
        url(r'^media/(?P<path>.*)$', static.serve, {'document_root': settings.MEDIA_ROOT }, name='media')
]

urlpatterns += [
    url(r'^', include("home.urls", namespace="home")),
]

urlpatterns += staticfiles_urlpatterns()




@login_required
def protected_serve(request, path, document_root=None, show_indexes=False):
    return serve(request, path, document_root, show_indexes)


if settings.DEBUG is False:   #if DEBUG is True it will be served automatically
    urlpatterns += [
        url(r'^static/(?P<path>.*)$', static.serve, {'document_root': settings.STATIC_ROOT }, name='static'),
        url(r'^media/(?P<path>.*)$', static.serve, {'document_root': settings.MEDIA_ROOT }, name='media')
    ]
urlpatterns += staticfiles_urlpatterns()

home/forms.py
import os

from django import forms
from django.utils.translation import ugettext as _

import pyrebase
from django.conf import settings
from firebase_admin import firestore
from geoposition.forms import GeopositionField

from home.functions import check_dict_key

firebase = pyrebase.initialize_app(settings.FB_CONFIG)
auth_fb = firebase.auth()
database_fb = firebase.database()

# from .views import store



user_type_choice = (
    ('','User Type'),
    (1,'Admin'),
    (2,'Customer'),
    (3,'Employee'),
)

class LoginForm(forms.Form):
    username_or_email = forms.EmailField(max_length=255,min_length=2,required=True,widget=forms.EmailInput(attrs={'placeholder':_('Email'),'autocomplete':'off','class': 'form-control form-control-solid placeholder-no-fix',}))
    password = forms.CharField(max_length=255,required=True,widget=forms.PasswordInput(attrs={'placeholder':_('Password'),'autocomplete':'off','class': 'form-control form-control-solid placeholder-no-fix',}))
    remember_me = forms.BooleanField(required=False)

class SignupForm(forms.Form):
    name = forms.CharField(max_length=255,min_length=2,required=True,widget=forms.TextInput(attrs={'autocomplete':'off','class': 'form-control',}))
    email = forms.EmailField(max_length=255,required=True,widget=forms.EmailInput(attrs={'autocomplete':'off','class': 'form-control',}))
    password = forms.CharField(max_length=255,min_length=6,required=True,widget=forms.PasswordInput(attrs={'autocomplete':'off','class': 'form-control',}))
    code = forms.CharField(max_length=255,min_length=2,required=False,widget=forms.TextInput(attrs={'autocomplete':'off','class': 'form-control',}))
    address = forms.CharField(max_length=255,min_length=2,required=False,widget=forms.TextInput(attrs={'autocomplete':'off','class': 'form-control',}))
    post_code = forms.CharField(max_length=255,min_length=2,required=False,widget=forms.TextInput(attrs={'autocomplete':'off','class': 'form-control',}))
    city = forms.CharField(max_length=255,min_length=2,required=False,widget=forms.TextInput(attrs={'autocomplete':'off','class': 'form-control',}))
    phone = forms.CharField(max_length=255,min_length=2,required=False,widget=forms.TextInput(attrs={'autocomplete':'off','class': 'form-control',}))
    image = forms.ImageField(required=False)
    document = forms.FileField(required=False)
    address_document = forms.FileField(required=False)
    contract_file = forms.FileField(required=False)
    user_type = forms.ChoiceField(required=True,choices=user_type_choice,widget=forms.Select(attrs={'autocomplete':'off','class': 'form-control',}))


class UserEditForm(forms.Form):
    name = forms.CharField(max_length=255,min_length=2,required=True,widget=forms.TextInput(attrs={'autocomplete':'off','class': 'form-control',}))
    code = forms.CharField(max_length=255,min_length=2,required=True,widget=forms.TextInput(attrs={'autocomplete':'off','class': 'form-control',}))
    password = forms.CharField(max_length=255,min_length=6,required=False,widget=forms.PasswordInput(attrs={'autocomplete':'off','class': 'form-control',}))
    address = forms.CharField(max_length=255,min_length=2,required=False,widget=forms.TextInput(attrs={'autocomplete':'off','class': 'form-control',}))
    post_code = forms.CharField(max_length=255,min_length=2,required=False,widget=forms.TextInput(attrs={'autocomplete':'off','class': 'form-control',}))
    city = forms.CharField(max_length=255,min_length=2,required=False,widget=forms.TextInput(attrs={'autocomplete':'off','class': 'form-control',}))
    phone = forms.CharField(max_length=255,min_length=2,required=False,widget=forms.TextInput(attrs={'autocomplete':'off','class': 'form-control',}))
    image = forms.ImageField(required=False)
    document = forms.FileField(required=False)
    address_document = forms.FileField(required=False)
    contract_file = forms.FileField(required=False)
    # user_type = forms.ChoiceField(required=True,choices=user_type_choice,widget=forms.Select(attrs={'autocomplete':'off','class': 'form-control',}))

class CustomerEmployeeForm(forms.Form):
    place = forms.ChoiceField(required=True,choices=[],widget=forms.Select(attrs={'autocomplete':'off','class': 'form-control select2',}))
    employees = forms.MultipleChoiceField(required=True,choices=[],widget=forms.SelectMultiple(attrs={'autocomplete':'off','class': 'form-control select2-multiple'}))
    start_date = forms.DateTimeField(required=True,widget=forms.TextInput(attrs={'autocomplete':'off','class': 'form-control','size':10,'readonly':'',}))
    end_date = forms.DateTimeField(required=True,widget=forms.TextInput(attrs={'autocomplete':'off','class': 'form-control','size':16,'readonly':'',}))
    def __init__(self,*args, **kwargs):
        super(CustomerEmployeeForm, self).__init__(*args, **kwargs)
        # all_customers_list = []
        all_places_list = []
        all_employees_list = []
        store = firestore.client()
        all_places = store.collection(u'places').get()
        # all_customers = store.collection(u'customers').get()
        all_employees = store.collection(u'employees').get()
        # all_employees_list = []
        for all_places_item in all_places:
            all_places_item_val = all_places_item.to_dict()
            try:
                customer_item = check_dict_key(all_places_item_val, 'customerRef').get().to_dict()
            except:
                customer_item = None

            if check_dict_key(all_places_item_val, 'deleted'):
                continue
            all_places_list.append([all_places_item.id,"{}  --  {}".format(customer_item['name'] if customer_item else 'Adminstration',check_dict_key(all_places_item_val,'name'))])
        #
        # for all_customers_item in all_customers:
        #     all_customers_item_val = all_customers_item.to_dict()
        #     all_customers_list.append([all_customers_item.id,"{}".format(check_dict_key(all_customers_item_val,'name'))])

        for all_employees_item in all_employees:
            all_employees_item_val = all_employees_item.to_dict()
            if check_dict_key(all_employees_item_val, 'deleted'):
                continue
            all_employees_list.append([all_employees_item.id,"{}".format(check_dict_key(all_employees_item_val,'name'))])

        self.fields['place'].choices = [['',_('Choose Place')]] + all_places_list
        self.fields['employees'].choices = [['',_('Choose Employee')]] + all_employees_list

class EmployeePageWorkSearchForm(forms.Form):
    start_date = forms.CharField(required=False,widget=forms.DateInput(attrs={'autocomplete':'off','class': 'form-control ','placeholder':'From'}))
    end_date = forms.CharField(required=False,widget=forms.DateInput(attrs={'autocomplete':'off','class': 'form-control','placeholder':'To',}))
    def __init__(self,*args, **kwargs):
        super(EmployeePageWorkSearchForm, self).__init__(*args, **kwargs)


class EmployeeWorkSearchForm(forms.Form):
    employee = forms.ChoiceField(required=True,choices=[],widget=forms.Select(attrs={'autocomplete':'off','class': 'form-control select2','placeholder':'Employee'}))
    start_date = forms.CharField(required=False,widget=forms.DateInput(attrs={'autocomplete':'off','class': 'form-control ','placeholder':'From'}))
    end_date = forms.CharField(required=False,widget=forms.DateInput(attrs={'autocomplete':'off','class': 'form-control','placeholder':'To',}))
    def __init__(self,user_type,user_id,*args, **kwargs):
        super(EmployeeWorkSearchForm, self).__init__(*args, **kwargs)
        store = firestore.client()
        all_users = store.collection(u'employees').get()
        all_employees_list = []
        try:
            for all_users_item in all_users:
                all_users_item_val = all_users_item.to_dict()
                if check_dict_key(all_users_item_val, 'deleted'):
                    continue
                all_employees_list.append([all_users_item.id,"{}".format(all_users_item_val['name'])])

                    # # print("all_users_item.val() = {} ".format(all_users_item.val()))
        except:
            pass
        self.fields['employee'].choices = all_employees_list



class WorkSearchForm(forms.Form):
    customer = forms.ChoiceField(required=False,choices=[],widget=forms.Select(attrs={'autocomplete':'off','class': 'form-control select2','placeholder':'Customer',}))
    date = forms.CharField(required=False,widget=forms.DateInput(attrs={'autocomplete':'off','class': 'form-control ','placeholder':'Date'}))
    def __init__(self,*args, **kwargs):
        super(WorkSearchForm, self).__init__(*args, **kwargs)
        store = firestore.client()
        all_users = store.collection(u'customers').get()
        all_customers_list = []
        for all_users_item in all_users:
            all_users_item_val = all_users_item.to_dict()
            if check_dict_key(all_users_item_val, 'deleted'):
                continue
            all_customers_list.append([all_users_item.id,"{}".format(check_dict_key(all_users_item_val,'name'))])
        self.fields['customer'].choices = [['',_('Choose Customer')]] + all_customers_list
        #


class PlaceSearchForm(forms.Form):
    customer = forms.ChoiceField(required=False,choices=[],widget=forms.Select(attrs={'autocomplete':'off','class': 'form-control select2','placeholder':'Customer',}))
    # date = forms.CharField(required=False,widget=forms.DateInput(attrs={'autocomplete':'off','class': 'form-control ','placeholder':'Date'}))
    def __init__(self,*args, **kwargs):
        super(PlaceSearchForm, self).__init__(*args, **kwargs)
        store = firestore.client()
        all_users = store.collection(u'customers').get()
        all_customers_list = []
        for all_users_item in all_users:
            all_users_item_val = all_users_item.to_dict()
            if check_dict_key(all_users_item_val, 'deleted'):
                continue

templates/home/admin/customer-list.html
{% extends 'main_base.html' %}
{% load static %}
{% load i18n %}

{% block title_container %}
    {% trans 'Customers' %}
{% endblock %}


{% block head_container %}
{% endblock %}
{% block head_under_container %}

        <!-- BEGIN PAGE LEVEL PLUGINS -->
        <link href="{% static 'main/assets/global/plugins/datatables/datatables.min.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'main/assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css' %}" rel="stylesheet" type="text/css" />
        <!-- END PAGE LEVEL PLUGINS -->

{% endblock %}


{% block content_container %}

            <!-- BEGIN CONTENT -->
            <div class="page-content-wrapper">
                <!-- BEGIN CONTENT BODY -->
                <div class="page-content">
                    <!-- BEGIN PAGE HEAD-->
                    <div class="page-head">
                        <!-- BEGIN PAGE TITLE -->
                        <div class="page-title">
                            <h1>{% trans 'Customers' %}
{#                                <small>responsive extension demos</small>#}
                            </h1>
                        </div>
                        <!-- END PAGE TITLE -->
                    </div>
                    <!-- END PAGE HEAD-->
                    <!-- BEGIN PAGE BREADCRUMB -->
                    <ul class="page-breadcrumb breadcrumb">
                        <li>
                            <a href="{% url 'home:dashboard' %}">{% trans 'Dashboard' %}</a>
                            <i class="fa fa-circle"></i>
                        </li>
                        <li>
                            <span class="active">{% trans 'Customers' %}</span>
                        </li>
                    </ul>
                    <!-- END PAGE BREADCRUMB -->

                    <div class="row">
                        <div class="col-md-12">
                            <!-- BEGIN EXAMPLE TABLE PORTLET-->
                            <div class="portlet box red">
                                <div class="portlet-title">
                                    <div class="caption">
                                        <i class="fa fa-globe"></i>{% trans 'Customers List' %}</div>
                                    <div class="tools"> </div>
                                </div>
                                <div class="portlet-body">
                                    <table class="table table-striped table-bordered table-hover dt-responsive" width="100%" id="sample_4">
                                        <thead>
                                            <tr>
                                                <th class="all">/</th>
                                                <th class="all">Photo</th>
                                                <th class="all">Name</th>
                                                <th class="min-tablet">Phone</th>
                                                <th class="min-tablet">Status</th>
                                                <th class="min-tablet">/</th>
{#                                                <th class="none">User Type</th>#}
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for all_data_list_item in all_data_list %}
                                                <tr>
                                                    <td>{{ forloop.counter }}</td>
                                                    <td>
                                                        <a href="{% if all_data_list_item.image %}{{ all_data_list_item.image }}{% else %}{% static 'main/assets/pages/media/users/icon-user.png' %}{% endif %}" class="example-image-link" data-lightbox="example-1"><img class="example-image"  style="height:50px;" src="{% if all_data_list_item.image %}{{ all_data_list_item.image }}{% else %}{% static 'main/assets/pages/media/users/icon-user.png' %}{% endif %}"></a>
                                                    </td>
                                                    <td>{{ all_data_list_item.name }}</td>
                                                    <td>{{ all_data_list_item.phone }}</td>
                                                    <td>{% if all_data_list_item.status %}
                                                            <span class="badge badge-success"> ✓ </span>
                                                        {% else %}
                                                            <span class="badge badge-danger"> x </span>
                                                        {% endif %}
                                                    </td>
                                                    <td>
                                                        <a href="{% url 'home:customer-page' all_data_list_item.id %}" class="btn dark btn-sm btn-outline sbold uppercase">
                                                            <i class="fa fa-eye"></i> {% trans 'View' %} </a> |
                                                        <a href="{% url 'home:edit-user' 'customer' all_data_list_item.id %}" class="btn btn-outline btn-circle btn-sm purple">
                                                            <i class="fa fa-edit"></i> {% trans 'Edit' %} </a>
                                                    </td>
{#                                                    <td>#}
{#                                                        {{  }}#}
{#                                                    </td>#}
                                                </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <!-- END EXAMPLE TABLE PORTLET-->
                        </div>
                    </div>
                    <!-- END PAGE BASE CONTENT -->
                </div>
                <!-- END CONTENT BODY -->
            </div>
            <!-- END CONTENT -->

{% endblock %}


{% block js_block %}


        <!-- BEGIN PAGE LEVEL PLUGINS -->
        <script src="{% static 'main/assets/global/scripts/datatable.js' %}" type="text/javascript"></script>
        <script src="{% static 'main/assets/global/plugins/datatables/datatables.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'main/assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js' %}" type="text/javascript"></script>
        <!-- END PAGE LEVEL PLUGINS -->
        <!-- BEGIN THEME GLOBAL SCRIPTS -->
        <script src="{% static 'main/assets/global/scripts/app.min.js' %}" type="text/javascript"></script>
        <!-- END THEME GLOBAL SCRIPTS -->
        <!-- BEGIN PAGE LEVEL SCRIPTS -->
        <script src="{% static 'main/assets/pages/scripts/table-datatables-responsive.min.js' %}" type="text/javascript"></script>
        <!-- END PAGE LEVEL SCRIPTS -->

{% endblock %}

>

templates/home/admin/employee-list.html
{% extends 'main_base.html' %}

{% block title_container %}

{% endblock %}

{% block head_container %}

{% endblock %}


{% block content_container %}



{% endblock %}


{% block js_block %}

{% endblock %}

templates/home/admin/place-form.html
{% extends 'main_base.html' %}
{% load i18n %}
{% load static %}
{% block title_container %}
                                    {% trans 'Place' %} - {% if place_obj %}{% trans 'Edit' %}{% else %}{% trans 'Create' %}{% endif %}
{% endblock %}


{% block head_container %}
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/6.6.5/sweetalert2.min.css" type="text/css"/>
{#        <link href="{% static 'geoposition/geoposition.css' %}" type="text/css" media="all" rel="stylesheet"/>#}
        {{ place_form.media }}
{% endblock %}


{% block content_container %}


    <!-- BEGIN CONTENT -->
    <div class="page-content-wrapper">
        <!-- BEGIN CONTENT BODY -->
        <div class="page-content">
            <!-- BEGIN PAGE BREADCRUMB -->
            <ul class="page-breadcrumb breadcrumb">
                <li>
                    <a href="{% url 'home:dashboard' %}">Dashboard</a>
                    <i class="fa fa-circle"></i>
                </li>
            </ul>
            <!-- END PAGE BREADCRUMB -->
            <!-- BEGIN PAGE BASE CONTENT -->
            <div class="row">
                <div class="col-md-12">
                    <!-- BEGIN VALIDATION STATES-->
                    <div class="portlet light portlet-fit portlet-form bordered">
                        <div class="portlet-title">
                            <div class="caption">
                                <i class=" icon-layers font-red"></i>
                                <span class="caption-subject font-red sbold uppercase">
                                    {% trans 'Place' %} - {% if place_obj %}{% trans 'Edit' %}{% else %}{% trans 'Create' %}{% endif %}
                                </span>
                            </div>
                        </div>
                        <div class="portlet-body">
                            <!-- BEGIN FORM-->
                            <form action="" method="post" enctype='multipart/form-data'>
                                {% csrf_token %}
                                <div class="form-body">
                                    <div class="form-group form-md-line-input form-md-floating-label">
                                        {{ place_form.customer }}
                                        <label for="id_customer">{% trans 'customer' %}</label>
                                        <span class="help-block">Some help goes here...</span>
                                        {% if place_form.customer.errors %}
                                            <div class="alert alert-danger" style="padding: 7px 0;">
                                                <button style="margin: 5px 10px;" type="button" class="close"
                                                        data-dismiss="alert" aria-hidden="true">
                                                    ×
                                                </button>
                                                <strong>{{ place_form.customer.errors }}</strong>
                                            </div>
                                        {% endif %}
                                    </div>
                                    <div class="form-group form-md-line-input form-md-floating-label">
                                        {{ place_form.name }}
                                        <label for="id_name">{% trans 'Name' %}</label>
                                        <span class="help-block">Some help goes here...</span>
                                        {% if place_form.name.errors %}
                                            <div class="alert alert-danger" style="padding: 7px 0;">
                                                <button style="margin: 5px 10px;" type="button" class="close"
                                                        data-dismiss="alert" aria-hidden="true">
                                                    ×
                                                </button>
                                                <strong>{{ place_form.name.errors }}</strong>
                                            </div>
                                        {% endif %}
                                    </div>
                                    <div class="form-group form-md-line-input form-md-floating-label">
                                        {{ place_form.address }}
                                        <label for="id_address">{% trans 'Address' %}</label>
                                        <span class="help-block">Some help goes here...</span>
                                        {% if place_form.address.errors %}
                                            <div class="alert alert-danger" style="padding: 7px 0;">
                                                <button style="margin: 5px 10px;" type="button" class="close"
                                                        data-dismiss="alert" aria-hidden="true">
                                                    ×
                                                </button>
                                                <strong>{{ place_form.address.errors }}</strong>
                                            </div>
                                        {% endif %}
                                    </div>
                                    <div class="form-group form-md-line-input form-md-floating-label">

                                        <label for="id_address">{% trans 'Address' %}</label>
                                        {{ place_form.position }}
                                        {% if place_form.position.errors %}
                                            <div class="alert alert-danger" style="padding: 7px 0;">
                                                <button style="margin: 5px 10px;" type="button" class="close"
                                                        data-dismiss="alert" aria-hidden="true">
                                                    ×
                                                </button>
                                                <strong>{{ place_form.position.errors }}</strong>
                                            </div>
                                        {% endif %}
                                    </div>
                                </div>
                                <div class="form-actions">
                                    <div class="row">
                                        <div class="col-md-12">
                                            <button type="submit" class="btn dark">Submit</button>
                                            <a href="javascript:;" class="btn default">Cancel</a>
                                        </div>
                                    </div>
                                </div>
                            </form>
                            <!-- END FORM-->
                        </div>
                    </div>
                    <!-- END VALIDATION STATES-->
                </div>
            </div>
            <!-- END PAGE BASE CONTENT -->
        </div>
        <!-- END CONTENT BODY -->
    </div>
    <!-- END CONTENT -->

{% endblock %}


{% block js_block %}


        <script src="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/6.6.5/sweetalert2.min.js"></script>
    <script type="text/javascript" src="{% static 'geoposition/geoposition.js' %}"></script>


    {% if success_message %}
        <script>

            $(document).ready(function () {
                swal(
                    '{{ success_message }}',
                    '',
                    'success'
                );
            });

        </script>
    {% endif %}
{% endblock %}